project:
  type: website
  output-dir: docs

website:
  title: "_Computing Geographically_ Bonus Material"
  favicon: favicon.ico
  navbar: 
    left:
      - text: Chapters
        menu:
          - text: "1. Building Bridges"
            file: "chapters/chap1/index.qmd"
          - text: "2. Location and Space"
            file: "chapters/chap2/index.qmd"
          - text: "3. Scale and Projection"
            file: "chapters/chap3/index.qmd"
          - text: "4. Place and Meaning in Space"
            file: "chapters/chap4/index.qmd"
          - text: "5. Lines and Areas"
            file: "chapters/chap5/index.qmd"
          - text: "6. Relations, Networks, Flows"
            file: "chapters/chap6/index.qmd"
          - text: "7. Time and Dynamics"
            file: "chapters/chap7/index.qmd"
          - text: "8. Process and Pattern"
            file: "chapters/chap8/index.qmd"
          - text: "9. Doing Giscience Doing Geography"
            file: "chapters/chap9/index.qmd"
      - text: Odds and ends
        file: "posts.qmd"
      - text: All the pages
        file: "index-listing.qmd"
  page-navigation: true
  body-footer: "&copy; 2023 David O'Sullivan"

format:
  html:
    theme: journal
    css: styles.css
    toc: true
 
